environment:
    matrix:
        - PYTHON: Python27
        - PYTHON: Python34
        - PYTHON: Python35

install:
    - C:\%PYTHON%\Scripts\pip install -r requirements.txt -r requirements-test.txt

build: off

test_script:
    - C:\%PYTHON%\Scripts\pytest
