language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - pypy
    - pypy3

os: linux

install:
    - if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
        export RUN_COVERAGE=true;
        pip install coverage codecov pytest-cov;
        pip install yapf;
      fi
    - pip install -r requirements.txt

script:
    - if [[ $RUN_COVERAGE == true ]]; then
        python -m pytest --cov=cppdep --cov=graph --cov-config .coveragerc && codecov;
        yapf -d cppdep/*.py;
      else
        python -m pytest;
      fi
